//
//  HomeTabInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeTabBusinessLogic
{
  func doSomething(request: WebtoonHomeTab.WebtoonModel.Request)
}

protocol HomeTabDataStore
{
  //var name: String { get set }
}

class HomeTabInteractor: HomeTabBusinessLogic, HomeTabDataStore
{
  var presenter: HomeTabPresentationLogic?
  var worker: HomeTabWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WebtoonHomeTab.WebtoonModel.Request)
  {
    worker = HomeTabWorker()
    worker?.doSomeWork()
    
    let response = WebtoonHomeTab.WebtoonModel.Response()
    presenter?.presentSomething(response: response)
  }
}
