//
//  HomeTabPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeTabPresentationLogic
{
  func presentSomething(response: WebtoonHomeTab.WebtoonModel.Response)
}

class HomeTabPresenter: HomeTabPresentationLogic
{
  weak var viewController: HomeTabDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WebtoonHomeTab.WebtoonModel.Response)
  {
//    let viewModel = HomeTab.WebtoonModel.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
  }
}
