//
//  HomeTabModels.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonCollectionType {
    
}

enum WebtoonHomeTab {
    enum WebtoonHomeTabSection: Int {
        case recommand
        case week
        case webtoonList
    }
    enum WeekModel: WebtoonCollectionType {
        case new
        case everyDayPlus
        case mon
        case tue
        case wed
        case tur
        case fri
        case sat
        case sun
        case complete
    }
    
    enum WebtoonModel {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel: Hashable, WebtoonCollectionType {
            var title: String
            var author: String
            var img: String
            var isNew: Bool
            var isAdult: Bool
            var isRest: Bool
            var isUp: Bool
            var isOver15: Bool
            var isFree: Bool
            var isWaitFree: Bool
        }
    }
}
