//
//  HomeTabInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeBusinessLogic {
    init(errorHandler: WebtoonHomeServiceErrorHandler)
    func fetchWebtoons(request: WebtoonHomeModels.WebtoonModels.Request)
}

protocol WebtoonHomeDataStore {
    
}

class WebtoonHomeInteractor: WebtoonHomeBusinessLogic, WebtoonHomeDataStore {
    var presenter: WebtoonHomePresentationLogic?
    var worker: WebtoonHomeWorker?
    
    init() {
        worker = WebtoonHomeWorker()
    }
        
    required init(errorHandler: WebtoonHomeServiceErrorHandler) {
        worker = WebtoonHomeWorker()
        worker?.webtoonHomeServiceErrorHandler = errorHandler
    }
    
    func fetchWebtoons(request: WebtoonHomeModels.WebtoonModels.Request) {
        worker?.requestWetoons(request: request,
                               completion: { [weak self] response in
            guard let self = self else { return }
            presenter?.presentWebtoons(response: response)
        })
    }
}
