//
//  HomeTabInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeBusinessLogic
{
  func doSomething(request: WebtoonHomeModels.WebtoonModel.Request)
}

protocol WebtoonHomeDataStore
{
  //var name: String { get set }
}

class WebtoonHomeInteractor: WebtoonHomeBusinessLogic, WebtoonHomeDataStore
{
  var presenter: WebtoonHomePresentationLogic?
  var worker: WebtoonHomeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WebtoonHomeModels.WebtoonModel.Request)
  {
      worker = WebtoonHomeWorker()
    worker?.doSomeWork()
    
    let response = WebtoonHomeModels.WebtoonModel.Response()
    presenter?.presentSomething(response: response)
  }
}
