//
//  HomeTabWorker.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/07/27.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

final class WebtoonHomeWorker {
    weak var webtoonHomeServiceErrorHandler: WebtoonHomeServiceErrorHandler?
    
    func requestWetoons(request: WebtoonHomeModels.WebtoonModels.Request,
                        completion: @escaping (WebtoonHomeModels.WebtoonModels.Response) -> (Void)) {
//        WebtoonHomeService().fetchSpecificDayWebtoons(request: request) { [weak self] result in
//            guard let self = self else { return }
//            switch result {
//            case .success(let success):
//                completion(success)
//            case .failure(let failure):
//                self.webtoonHomeServiceErrorHandler?.errorHandling(error: failure)
//            }
//        }
    }
}
