//
//  WebtoonHomeRecommandationModels.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebtoonService

enum WebtoonHomeRecommandation {
    
    enum RecommandationWebtoonModel {
        struct Request: WebtoonRequestable {
            var page: Int
            var perPage: Int
            var service: WebtoonSupplier
            var updateDay: UpdateDay
            
            static var empty = Self.init()
            
            init(page: Int, perPage: Int, service: WebtoonSupplier, updateDay: UpdateDay) {
                self.page = page
                self.perPage = perPage
                self.service = service
                self.updateDay = updateDay
            }
            
            init() {
                page = 0
                perPage = 0
                service = .naver
                updateDay = .everyDayPlus
            }
        }
        struct Response: Decodable {
            var webtoons: [WebtoonModel]
        }
        
        struct WebtoonModel: Decodable {
            var title: String
            var author: String
            var url: String
            var img: String
            var service: String
            var updateDays: [String]
            var additional: ResponseAdditional
            
            static var empty = Self.init()
            
            init() {
                self.title = ""
                self.author = ""
                self.url = ""
                self.img = ""
                self.service = ""
                self.updateDays = []
                self.additional = ResponseAdditional.empty
            }
        }
        struct ResponseAdditional: Decodable {
            var new: Bool
            var adult: Bool
            var rest: Bool
            var up: Bool
            var singularityList: [String]
            
            static var empty = Self.init()
            
            init() {
                new = false
                adult = false
                rest = false
                up = false
                singularityList = []
            }
        }
        struct ViewModel: Hashable {
            var title: String
            var img: String
            
            init(title: String, img: String) {
                self.title = title
                self.img = img
            }
        }
    }
}
