//
//  WebtoonHomeRecommandationViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CustomUtility

protocol WebtoonHomeRecommandationDisplayLogic: AnyObject {
    func displayRecommandationWebtoons(viewModels: [WebtoonHomeRecommandation.RecommandationWebtoonModel.ViewModel])
}

class WebtoonHomeRecommandationViewController: UIViewController, WebtoonHomeRecommandationDisplayLogic {
    var interactor: WebtoonHomeRecommandationBusinessLogic?
    var router: (NSObjectProtocol & WebtoonHomeRecommandationRoutingLogic & WebtoonHomeRecommandationDataPassing)?
    
    private var recommandationWebtoons: [RecommandationView]
    private lazy var webtoonTitleCollectionView: UICollectionView = {
        let collectionView: UICollectionView = UICollectionView(frame: .zero, collectionViewLayout: createCollectionViewLayout())
        collectionView.bounces = false
        collectionView.backgroundColor = .clear
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        return collectionView
    }()
    private var collectionViewDataSource: CustomCollectionViewDatasource<RecommandWebtoonSection,
                                                                        WebtoonHomeRecommandation.RecommandationWebtoonModel.ViewModel,
                                                                        RecommandCollectionViewCell>?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        recommandationWebtoons = []
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
        setupView()
        setupDataSource()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WebtoonHomeRecommandationInteractor()
        let presenter = WebtoonHomeRecommandationPresenter()
        let router = WebtoonHomeRecommandationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupView() {
        view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(webtoonTitleCollectionView)
        NSLayoutConstraint.activate([
            webtoonTitleCollectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            webtoonTitleCollectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            webtoonTitleCollectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            webtoonTitleCollectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor)
        ])
    }
    
    private func createCollectionViewLayout() -> UICollectionViewCompositionalLayout {
        let item = NSCollectionLayoutItem(layoutSize: NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                                                             heightDimension: .fractionalHeight(0.22)))
        item.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 3, bottom: 0, trailing: 3)
        item.edgeSpacing = NSCollectionLayoutEdgeSpacing(leading: nil,
                                                         top: .flexible(1),
                                                         trailing: nil,
                                                         bottom: nil)
        let groupSize: NSCollectionLayoutSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.93),
                                                                       heightDimension: .fractionalHeight(1.0))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize, subitems: [item])
        let section = NSCollectionLayoutSection(group: group)
        section.orthogonalScrollingBehavior = .groupPagingCentered
        section.visibleItemsInvalidationHandler = { [weak self] (visibleItems, offset, env) in
            //TODO: collectionView 이동 시 이벤트 처리
        }
        return UICollectionViewCompositionalLayout(section: section)
    }
    
    private func setupRecommandationViews() {
        self.recommandationWebtoons.reversed().forEach {
            view.addSubview($0)
            $0.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                $0.topAnchor.constraint(equalTo: self.view.topAnchor),
                $0.bottomAnchor.constraint(equalTo: webtoonTitleCollectionView.bottomAnchor, constant: -5),
                $0.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
                $0.trailingAnchor.constraint(equalTo: self.view.trailingAnchor)
            ])
        }
    }
    
    private func setupDataSource() {
        self.collectionViewDataSource = CustomCollectionViewDatasource(collectionView: webtoonTitleCollectionView,
                                                                       completion: { cell, indexPath, item in
            cell.configureView(title: item.title)
        })
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchRecommandationWebtoon()
    }
    
    // MARK: Do something
    
    func fetchRecommandationWebtoon() {
        let request = WebtoonHomeRecommandation.RecommandationWebtoonModel.Request(page: 0,
                                                                                   perPage: 10,
                                                                                   service: .naver,
                                                                                   updateDay: .tue)
        interactor?.fetchRecommandationWebtoons(request: request)
    }
    
    func displayRecommandationWebtoons(viewModels: [WebtoonHomeRecommandation.RecommandationWebtoonModel.ViewModel]) {
        DispatchQueue.main.async { [weak self] in
            guard let self = self else {
                return
            }
            recommandationWebtoons = viewModels.map { _ in RecommandationView() }
            setupRecommandationViews()
            viewModels.enumerated().forEach { (index, value) in
                self.recommandationWebtoons[index].configureView(imageURL: value.img,
                                                                 title: value.title)
            }
            view.bringSubviewToFront(webtoonTitleCollectionView)
            collectionViewDataSource?.updateData(seciton: .main, models: viewModels)
        }
    }
}
