//
//  WebtoonHomeRecommandationInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeRecommandationBusinessLogic {
    func fetchRecommandationWebtoons(request: WebtoonHomeRecommandation.RecommandationWebtoonModel.Request)
}

protocol WebtoonHomeRecommandationDataStore {
}

class WebtoonHomeRecommandationInteractor: WebtoonHomeRecommandationBusinessLogic, WebtoonHomeRecommandationDataStore {
    var presenter: WebtoonHomeRecommandationPresentationLogic?
    var worker: WebtoonHomeRecommandationWorker?
    
    // MARK: Do something
    
    func fetchRecommandationWebtoons(request: WebtoonHomeRecommandation.RecommandationWebtoonModel.Request) {
        worker = WebtoonHomeRecommandationWorker()
        worker?.fetchRecommandationWebtoons(request: request,
                                            completion: { response in
            self.presenter?.presentRecommandationWebtoons(response: response)
        })
    }
}
