//
//  RecommandedCompletionPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/22.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecommandedCompletionPresentationLogic
{
  func presentSomething(response: RecommandedCompletion.Something.Response)
}

class RecommandedCompletionPresenter: RecommandedCompletionPresentationLogic
{
  weak var viewController: RecommandedCompletionDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RecommandedCompletion.Something.Response)
  {
    let viewModel = RecommandedCompletion.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
