//
//  WebtoonHomeWebtoonListPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeWebtoonListPresentationLogic
{
  func presentSomething(response: WebtoonHomeWebtoonList.Something.Response)
}

class WebtoonHomeWebtoonListPresenter: WebtoonHomeWebtoonListPresentationLogic
{
  weak var viewController: WebtoonHomeWebtoonListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WebtoonHomeWebtoonList.Something.Response)
  {
    let viewModel = WebtoonHomeWebtoonList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
