//
//  WebtoonHomePresenterTests.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/30.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest
import WebtoonHome

class WebtoonHomePresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: WebtoonHomeWebtoonListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupWebtoonHomePresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    func setupWebtoonHomePresenter() {
        sut = WebtoonHomeWebtoonListPresenter()
    }
    
    // MARK: Test doubles
    class WebtoonHomeDisplayLogicSpy: WebtoonHomeWebtoonListDisplayLogic {
        var displaySomethingCalled = false
        func displayWebtoonList(viewModel: [WebtoonHome.WebtoonHomeWebtoonList.WebtoonModels.ViewModel]) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    func testPresentWebtoons() {
        // Given
        let spy = WebtoonHomeDisplayLogicSpy()
        sut.viewController = spy
        let response = WebtoonHomeWebtoonList.WebtoonModels.Response()
        
        // When
        sut.presentWebtoons(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
