//
//  WebtoonHomeWorkerTests.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/30.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import XCTest
//
//class WebtoonHomeWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//
//  var sut: WebtoonHomeWorker!
//
//  // MARK: Test lifecycle
//
//  override func setUp()
//  {
//    super.setUp()
//    setupWebtoonHomeWorker()
//  }
//
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//
//  // MARK: Test setup
//
//  func setupWebtoonHomeWorker()
//  {
//    sut = WebtoonHomeWorker()
//  }
//
//  // MARK: Test doubles
//
//  // MARK: Tests
//
//  func testSomething()
//  {
//    // Given
//
//    // When
//
//    // Then
//  }
//}
