//
//  WebtoonHomePresenterTests.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/30.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import XCTest
//
//class WebtoonHomePresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: WebtoonHomePresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupWebtoonHomePresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupWebtoonHomePresenter()
//  {
//    sut = WebtoonHomePresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class WebtoonHomeDisplayLogicSpy: WebtoonHomeDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: WebtoonHome.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = WebtoonHomeDisplayLogicSpy()
//    sut.viewController = spy
//    let response = WebtoonHome.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
