
//WebtoonHomeViewControllerTests.swift
//CleanWebtoon
//
//Created by temp_name on 2023/08/30.
//Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//This file was generated by the Clean Swift Xcode Templates so
//you can apply clean architecture to your iOS and Mac projects,
//see http://clean-swift.com


import XCTest
import WebtoonHome

class WebtoonHomeViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: WebtoonHomeWebtoonListViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupWebtoonHomeViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupWebtoonHomeViewController() {
        sut = .init(targetDay: .mon,
                    interactor: WebtoonHomeWebtoonListInteractor(worker: WebtoonHomeWebtoonListWorker())
        )
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class WebtoonHomeBusinessLogicSpy: WebtoonHomeWebtoonListBusinessLogic {
        var doSomethingCalled = false
        func fetchWebtoonList(request: WebtoonHome.WebtoonHomeWebtoonList.WebtoonModels.Request) {
            doSomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func test_인터렉터의_함수를_잘_호출하는가() {
        // Given
        let spy = WebtoonHomeBusinessLogicSpy()
        sut = .init(targetDay: .mon,
                    interactor: spy)
        
        // When
        sut.viewDidLoad()
        
        // Then
        XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
    }
    
    func test_라우터의_함수를_잘_호출하는가() {
        
    }
}
