//
//  WebtoonHomeViewControllerTests.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/30.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import XCTest
//
//class WebtoonHomeViewControllerTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: WebtoonHomeViewController!
//  var window: UIWindow!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    window = UIWindow()
//    setupWebtoonHomeViewController()
//  }
//  
//  override func tearDown()
//  {
//    window = nil
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupWebtoonHomeViewController()
//  {
//    let bundle = Bundle.main
//    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
//    sut = storyboard.instantiateViewController(withIdentifier: "WebtoonHomeViewController") as! WebtoonHomeViewController
//  }
//  
//  func loadView()
//  {
//    window.addSubview(sut.view)
//    RunLoop.current.run(until: Date())
//  }
//  
//  // MARK: Test doubles
//  
//  class WebtoonHomeBusinessLogicSpy: WebtoonHomeBusinessLogic
//  {
//    var doSomethingCalled = false
//    
//    func doSomething(request: WebtoonHome.Something.Request)
//    {
//      doSomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testShouldDoSomethingWhenViewIsLoaded()
//  {
//    // Given
//    let spy = WebtoonHomeBusinessLogicSpy()
//    sut.interactor = spy
//    
//    // When
//    loadView()
//    
//    // Then
//    XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
//  }
//  
//  func testDisplaySomething()
//  {
//    // Given
//    let viewModel = WebtoonHome.Something.ViewModel()
//    
//    // When
//    loadView()
//    sut.displaySomething(viewModel: viewModel)
//    
//    // Then
//    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
//  }
//}
