//
//  WebtoonHomeRecommandationWorker.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WebtoonHomeRecommandationWorker {
    weak var webtoonHomeServiceErrorHandler: WebtoonHomeServiceErrorHandler?
    func fetchRecommandationWebtoons(request: WebtoonHomeRecommandation.RecommandationWebtoonModel.Request,
                                     completion: @escaping (WebtoonHomeRecommandation.RecommandationWebtoonModel.Response) -> (Void)) {
        RecommandationWebtoonFetchService().fetchRecommandWebtoons(requestModel: request) { result in
            switch result {
            case .success(let success):
                completion(success)
            case .failure(let failure):
                self.webtoonHomeServiceErrorHandler?.errorHandling(error: failure)
            }
        }
    }
}
