//
//  WebtoonHomeRecommandationInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeRecommandationBusinessLogic
{
  func doSomething(request: WebtoonHomeRecommandation.Something.Request)
}

protocol WebtoonHomeRecommandationDataStore
{
  //var name: String { get set }
}

class WebtoonHomeRecommandationInteractor: WebtoonHomeRecommandationBusinessLogic, WebtoonHomeRecommandationDataStore
{
  var presenter: WebtoonHomeRecommandationPresentationLogic?
  var worker: WebtoonHomeRecommandationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: WebtoonHomeRecommandation.Something.Request)
  {
    worker = WebtoonHomeRecommandationWorker()
    worker?.doSomeWork()
    
    let response = WebtoonHomeRecommandation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
