//
//  WebtoonHomeRecommandationViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeRecommandationDisplayLogic: AnyObject {
    func displaySomething(viewModel: WebtoonHomeRecommandation.Something.ViewModel)
}

class WebtoonHomeRecommandationViewController: UIViewController, WebtoonHomeRecommandationDisplayLogic {
    var interactor: WebtoonHomeRecommandationBusinessLogic?
    var router: (NSObjectProtocol & WebtoonHomeRecommandationRoutingLogic & WebtoonHomeRecommandationDataPassing)?
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
        setupViews()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WebtoonHomeRecommandationInteractor()
        let presenter = WebtoonHomeRecommandationPresenter()
        let router = WebtoonHomeRecommandationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupViews() {
        view.translatesAutoresizingMaskIntoConstraints = false
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething() {
        let request = WebtoonHomeRecommandation.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: WebtoonHomeRecommandation.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
