//
//  WebtoonDetailListViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonDetailListDisplayLogic: AnyObject {
    func displayDetailWebtoonList(viewModel: [WebtoonDetailList.DetailList.ViewModel])
}

class WebtoonDetailListViewController: UIViewController, WebtoonDetailListDisplayLogic {
    var interactor: WebtoonDetailListBusinessLogic?
    var router: (NSObjectProtocol & WebtoonDetailListRoutingLogic & WebtoonDetailListDataPassing)?
    
    // MARK: Object lifecycle
    private let decorationView: UIView
    private let thumbnailImage: UIImageView
    
    private let entireStackView: UIStackView
    private let webtoonTitle: UILabel
    private let authorWeekStack: UIStackView
    private let author: UILabel
    private let weekDay: UILabel
    
    private lazy var detailListView: UICollectionView = {
        let collectionView: UICollectionView = UICollectionView(frame: .zero, collectionViewLayout: createLayout())
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        collectionView.bounces = false
        collectionView.backgroundColor = .white
        collectionView.showsVerticalScrollIndicator = false
        collectionView.contentInsetAdjustmentBehavior = .never
        return collectionView
    }()
    private var dataSource: CustomCollectionViewDatasource<DetailListSection,
                                                           WebtoonDetailList.DetailList.ViewModel,
                                                           DetailListCell>?
    private let collectionViewDelegate: UICollectionViewDelegate
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        decorationView = {
            let view = UIView()
            view.translatesAutoresizingMaskIntoConstraints = false
            view.backgroundColor = .systemGray6
            return view
        }()
        thumbnailImage = {
            let imageView = UIImageView()
            imageView.image = UIImage(named: "default_icon")
            imageView.translatesAutoresizingMaskIntoConstraints = false
            return imageView
        }()
        entireStackView = {
            let stackView = UIStackView()
            stackView.translatesAutoresizingMaskIntoConstraints = false
            stackView.axis = .vertical
            return stackView
        }()
        webtoonTitle = {
            let label = UILabel()
            label.translatesAutoresizingMaskIntoConstraints = false
            return label
        }()
        authorWeekStack = {
            let stackView = UIStackView()
            stackView.distribution = .equalSpacing
            stackView.spacing = 5
            stackView.axis = .horizontal
            stackView.alignment = .leading
            stackView.translatesAutoresizingMaskIntoConstraints = false
            return stackView
        }()
        author = {
            let label = UILabel()
            label.translatesAutoresizingMaskIntoConstraints = false
            return label
        }()
        weekDay = {
            let label = UILabel()
            label.translatesAutoresizingMaskIntoConstraints = false
            return label
        }()
        collectionViewDelegate = WebtoonDetailListCollectionViewDelegate()
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
        setupCollectionView()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WebtoonDetailListInteractor()
        let presenter = WebtoonDetailListPresenter()
        let router = WebtoonDetailListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupViews() {
        self.navigationController?.navigationBar.isHidden = false
        let backButton: UIBarButtonItem = {
            let buttonItem = UIBarButtonItem()
            buttonItem.title = ""
            buttonItem.tintColor = .black
            return buttonItem
        }()
        self.navigationController?.navigationBar.topItem?.backBarButtonItem = backButton
        view.backgroundColor = .white
        
        self.view.addSubview(decorationView)
        self.view.addSubview(thumbnailImage)
        self.view.addSubview(entireStackView)
        self.entireStackView.addArrangedSubview(webtoonTitle)
        self.entireStackView.addArrangedSubview(authorWeekStack)
        self.authorWeekStack.addArrangedSubview(author)
        self.authorWeekStack.addArrangedSubview(weekDay)
        self.view.addSubview(detailListView)
        
        NSLayoutConstraint.activate([
            decorationView.topAnchor.constraint(equalTo: self.view.topAnchor),
            decorationView.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor),
            decorationView.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor),
            
            thumbnailImage.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor),
            thumbnailImage.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor, constant: 20),
            thumbnailImage.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor, constant: -20),
            thumbnailImage.heightAnchor.constraint(equalToConstant: 210),
            
            decorationView.bottomAnchor.constraint(equalTo: thumbnailImage.centerYAnchor, constant: -10),
            entireStackView.topAnchor.constraint(equalTo: thumbnailImage.bottomAnchor, constant: 5),
            entireStackView.leadingAnchor.constraint(equalTo: thumbnailImage.leadingAnchor),
            entireStackView.trailingAnchor.constraint(equalTo: thumbnailImage.trailingAnchor),
            
            detailListView.topAnchor.constraint(equalTo: entireStackView.bottomAnchor, constant: 10),
            detailListView.leadingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.leadingAnchor),
            detailListView.bottomAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.bottomAnchor),
            detailListView.trailingAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.trailingAnchor)
        ])
    }
    
    private func createLayout() -> UICollectionViewLayout {
        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                              heightDimension: .fractionalHeight(1.0))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)

        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                               heightDimension: .fractionalHeight(0.15))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize,
                                                       subitems: [item])

        let section = NSCollectionLayoutSection(group: group)
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout
    }
    
    private func setupCollectionView() {
        self.dataSource = CustomCollectionViewDatasource(collectionView: detailListView,
                                                         completion: { cell, IndexPath, itemType in
            cell.configureView(viewModel: itemType)
            cell.routingEventlistener = self
        })
        detailListView.delegate = collectionViewDelegate
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        fetchWebtoonDetailList()
    }
    
    // MARK: Do something
    
    private func hiddenDecorationView() {
        decorationView.isHidden = true
    }
    
    private func showDecorationView() {
        decorationView.isHidden = false
    }
    
    func fetchWebtoonDetailList() {
        interactor?.fetchWebtoonDetailList()
    }
    
    func displayDetailWebtoonList(viewModel: [WebtoonDetailList.DetailList.ViewModel]) {
        dataSource?.updateData(seciton: .main,
                               models: viewModel)
    }
}

extension WebtoonDetailListViewController: WebtoonBodyRoutingEventListener {
    func routeToBody(webtoonListIndex: Int) {
        router?.routeToWebtoonBody(webtoonIndex: webtoonListIndex)
    }
}
