//
//  WebtoonDetailListInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonDetailListBusinessLogic
{
    func doSomething(request: WebtoonDetailList.Something.Request)
}

protocol WebtoonDetailListDataStore
{
    //var name: String { get set }
}

class WebtoonDetailListInteractor: WebtoonDetailListBusinessLogic, WebtoonDetailListDataStore
{
    var presenter: WebtoonDetailListPresentationLogic?
    var worker: WebtoonDetailListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: WebtoonDetailList.Something.Request)
    {
        worker = WebtoonDetailListWorker()
        worker?.doSomeWork()
        
        let response = WebtoonDetailList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
