//
//  WebtoonDetailListRouter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WebtoonDetailListRoutingLogic {
    func routeToWebtoonBody(webtoonIndex: Int)
}

protocol WebtoonDetailListDataPassing
{
  var dataStore: WebtoonDetailListDataStore? { get }
}

class WebtoonDetailListRouter: NSObject, WebtoonDetailListRoutingLogic, WebtoonDetailListDataPassing {
    
    weak var viewController: WebtoonDetailListViewController?
    var dataStore: WebtoonDetailListDataStore?
  
  // MARK: Routing
    func routeToWebtoonBody(webtoonIndex: Int) {
        
    }

  // MARK: Navigation
//    func navigationToWebtoonBody(source: WebtoonDetailListViewController)
    
  //func navigateToSomewhere(source: WebtoonDetailListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: WebtoonDetailListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
