//
//  WebtoonDetailListPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonDetailListPresentationLogic
{
  func presentSomething(response: WebtoonDetailList.Something.Response)
}

class WebtoonDetailListPresenter: WebtoonDetailListPresentationLogic
{
  weak var viewController: WebtoonDetailListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WebtoonDetailList.Something.Response)
  {
    let viewModel = WebtoonDetailList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
