//
//  WebtoonDetailListRouter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WebtoonDetailListRoutingLogic {
    func routeToWebtoonBody(webtoonIndex: Int)
}

protocol WebtoonDetailListDataPassing {
    var dataStore: WebtoonDetailListDataStore? { get }
}

class WebtoonDetailListRouter: NSObject, WebtoonDetailListRoutingLogic, WebtoonDetailListDataPassing {
    
    weak var viewController: WebtoonDetailListViewController?
    var dataStore: WebtoonDetailListDataStore?
    
    // MARK: Routing
    func routeToWebtoonBody(webtoonIndex: Int) {
        let nxtViewController: WebtoonBodyViewController = WebtoonBodyViewController()
        var dataStore = nxtViewController.router!.dataStore!
        self.dataStore?.index = webtoonIndex
        passDataToWebtoonBody(source: self.dataStore!, destination: &dataStore)
        navigationToWebtoonBody(source: self.viewController!, destination: nxtViewController)
    }
    
    // MARK: Navigation
    func navigationToWebtoonBody(source: WebtoonDetailListViewController, destination: WebtoonBodyViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToWebtoonBody(source: WebtoonDetailListDataStore, destination: inout WebtoonBodyDataStore) {
        destination.webtoonTitle = source.fetchTarget
        destination.webtoonIndex = source.index
    }
}
