//
//  WebtoonBodyViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/28.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonBodyDisplayLogic: AnyObject {
    func displaySomething(viewModel: WebtoonBody.Something.ViewModel)
}

class WebtoonBodyViewController: UIViewController, WebtoonBodyDisplayLogic {
    var interactor: WebtoonBodyBusinessLogic?
    var router: (NSObjectProtocol & WebtoonBodyRoutingLogic & WebtoonBodyDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
        setupViews()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WebtoonBodyInteractor()
        let presenter = WebtoonBodyPresenter()
        let router = WebtoonBodyRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupViews() {
        self.view.backgroundColor = .white
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething() {
        let request = WebtoonBody.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: WebtoonBody.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
