//
//  WebtoonBodyInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/28.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonBodyBusinessLogic {
    func doSomething(request: WebtoonBody.Something.Request)
}

protocol WebtoonBodyDataStore {
    var webtoonTitle: String { get set }
    var webtoonIndex: Int { get set }
}

class WebtoonBodyInteractor: WebtoonBodyBusinessLogic, WebtoonBodyDataStore {
    var presenter: WebtoonBodyPresentationLogic?
    var worker: WebtoonBodyWorker?
    var webtoonTitle: String
    var webtoonIndex: Int
    
    init() {
        webtoonTitle = ""
        webtoonIndex = 0
    }
    
    // MARK: Do something
    
    func doSomething(request: WebtoonBody.Something.Request) {
        worker = WebtoonBodyWorker()
        worker?.doSomeWork()
        
        let response = WebtoonBody.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
