//
//  WebtoonBodyWorker.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/28.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WebtoonBodyWorker
{
  func doSomeWork()
  {
  }
}
