//
//  WebtoonDetailListPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonDetailListPresentationLogic {
    func presentWebtoonDetailList(response: WebtoonDetailList.DetailList.Response)
}

class WebtoonDetailListPresenter: WebtoonDetailListPresentationLogic {
    weak var viewController: WebtoonDetailListDisplayLogic?
    
    // MARK: Do something
    
    func presentWebtoonDetailList(response: WebtoonDetailList.DetailList.Response) {
        let viewModels = response.webtoonList.map({
            return WebtoonDetailList.DetailList.ViewModel(title: $0.title,
                                                          subTitle: $0.subTitle,
                                                          rating: $0.rating,
                                                          date: $0.date)
        })
        viewController?.displayDetailWebtoonList(viewModel: viewModels)
    }
}
