//
//  WebtoonDetailListWorker.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WebtoonDetailListWorker {
    //TODO: 에러 핸들러 설정
    
    func fetchDetailList(target: WebtoonDetailList.DetailList.Request,
                         completion: @escaping (WebtoonDetailList.DetailList.Response) -> Void) {
        WebtoonDetailListFetchService().requestWebtoonDetailList(request: target) { result in
            switch result {
            case .success(let success):
                completion(success)
            case .failure(let failure):
                //TODO: 에러 던지기
                print(failure)
            }
        }
    }
}
