//
//  WebtoonHomeRouter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/22.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WebtoonHomeRoutingLogic {
    func routeToDeatilListViewController(target: String)
}

protocol WebtoonHomeDataPassing {
}

class WebtoonHomeRouter: NSObject, WebtoonHomeRoutingLogic, WebtoonHomeDataPassing {
    weak var viewController: WebtoonHomeViewController?
    
    // MARK: Routing
    func routeToDeatilListViewController(target: String) {
        let destinationViewController = WebtoonDetailListViewController()
        var destinationDataStore = destinationViewController.router!.dataStore!
        passToData(source: target, destination: &destinationDataStore)
        pushToDestinationViewController(destinationViewController)
    }
    
    // MARK: Navigation
    func pushToDestinationViewController(_ viewcontroller: WebtoonDetailListViewController) {
        viewController?.navigationController?.pushViewController(viewcontroller, animated: true)
    }
    
    // MARK: Passing data
    func passToData(source: String, destination: inout WebtoonDetailListDataStore) {
        destination.fetchTarget = source
    }
}
