//
//  WebtoonHomeWebtoonListInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public protocol WebtoonHomeWebtoonListBusinessLogic {
    func fetchWebtoonList(request: WebtoonHomeWebtoonList.WebtoonModels.Request)
}

protocol WebtoonHomeWebtoonListDataStore {
    
}

public class WebtoonHomeWebtoonListInteractor: WebtoonHomeWebtoonListBusinessLogic, WebtoonHomeWebtoonListDataStore {
    public var presenter: WebtoonHomeWebtoonListPresentationLogic?
    private let worker: WebtoonListWorker?
    
    // MARK: Do something
    
    public init(worker: WebtoonListWorker) {
        self.worker = worker
    }
    
    public func fetchWebtoonList(request: WebtoonHomeWebtoonList.WebtoonModels.Request) {
        worker?.requestWetoons(request: request,
                               completion: { response in
            self.presenter?.presentWebtoons(response: response)
        })
    }
}
