//
//  WebtoonHomeWebtoonListWorker.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol WebtoonHomeServiceErrorHandler: AnyObject {
    func errorHandling(error: Error)
}

public protocol WebtoonListWorker {
    func requestWetoons(request: WebtoonHomeWebtoonList.WebtoonModels.Request,
                               completion: @escaping (WebtoonHomeWebtoonList.WebtoonModels.Response) -> (Void))
}

public class WebtoonHomeWebtoonListWorker: WebtoonListWorker {
    weak var webtoonHomeServiceErrorHandler: WebtoonHomeServiceErrorHandler?
    
    public init() {
        
    }
    
    public func requestWetoons(request: WebtoonHomeWebtoonList.WebtoonModels.Request,
                               completion: @escaping (WebtoonHomeWebtoonList.WebtoonModels.Response) -> (Void)) {
        WebtoonListFetchService().fetchSpecificDayWebtoons(request: request) { [weak self] result in
            guard let self = self else { return }
            switch result {
            case .success(let success):
                completion(success)
            case .failure(let failure):
                self.webtoonHomeServiceErrorHandler?.errorHandling(error: failure)
            }
        }
    }
}
