//
//  WebtoonHomeWebtoonListPresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/16.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeWebtoonListPresentationLogic {
    func presentWebtoons(response: WebtoonHomeWebtoonList.WebtoonModels.Response)
}

class WebtoonHomeWebtoonListPresenter: WebtoonHomeWebtoonListPresentationLogic {
  weak var viewController: WebtoonHomeWebtoonListDisplayLogic?
  
  // MARK: Do something
  
  func presentWebtoons(response: WebtoonHomeWebtoonList.WebtoonModels.Response) {
      let viewModels: [WebtoonHomeWebtoonList.WebtoonModels.ViewModel] = response.webtoons.map {
          let isOver15: Bool = $0.additional.singularityList.contains("over15")
          let isFree: Bool = $0.additional.singularityList.contains("free")
          let isWaitFree: Bool = $0.additional.singularityList.contains("waitFree")
          
          return WebtoonHomeWebtoonList.WebtoonModels.ViewModel(title: $0.title,
                                                                author: $0.author,
                                                                img: $0.img,
                                                                isNew: $0.additional.new,
                                                                isAdult: $0.additional.adult,
                                                                isRest: $0.additional.rest,
                                                                isUp: $0.additional.up,
                                                                isOver15: isOver15,
                                                                isFree: isFree,
                                                                isWaitFree: isWaitFree)
      }
      viewController?.displayWebtoonList(viewModel: viewModels)
  }
}
