//
//  ServiceCaseModels.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/08/08.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

public enum WebtoonSupplier: String {
    case naver
    case kakao
    case kakaoPage
}
