//
//  WebtoonHomePresenter.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomePresentationLogic
{
  func presentSomething(response: WebtoonHome.Something.Response)
}

class WebtoonHomePresenter: WebtoonHomePresentationLogic
{
  weak var viewController: WebtoonHomeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: WebtoonHome.Something.Response)
  {
    let viewModel = WebtoonHome.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
