//
//  RecommandedCompletionInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/22.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecommandedCompletionBusinessLogic
{
  func doSomething(request: RecommandedCompletion.Something.Request)
}

protocol RecommandedCompletionDataStore
{
  //var name: String { get set }
}

class RecommandedCompletionInteractor: RecommandedCompletionBusinessLogic, RecommandedCompletionDataStore
{
  var presenter: RecommandedCompletionPresentationLogic?
  var worker: RecommandedCompletionWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RecommandedCompletion.Something.Request)
  {
    worker = RecommandedCompletionWorker()
    worker?.doSomeWork()
    
    let response = RecommandedCompletion.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
