//
//  RecommandedCompletionViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/22.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecommandedCompletionDisplayLogic: class
{
  func displaySomething(viewModel: RecommandedCompletion.Something.ViewModel)
}

class RecommandedCompletionViewController: UIViewController, RecommandedCompletionDisplayLogic
{
  var interactor: RecommandedCompletionBusinessLogic?
  var router: (NSObjectProtocol & RecommandedCompletionRoutingLogic & RecommandedCompletionDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
      setupViews()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = RecommandedCompletionInteractor()
    let presenter = RecommandedCompletionPresenter()
    let router = RecommandedCompletionRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
    private func setupViews() {
        title = "추천완결"
        tabBarItem = UITabBarItem(title: "추천완결", image: UIImage(systemName: "lamp.table"), selectedImage: UIImage(systemName: "lamp.table.fill"))
        view.backgroundColor = .white
    }
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = RecommandedCompletion.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: RecommandedCompletion.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
