//
//  WebtoonHomeViewController.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeDisplayLogic: AnyObject
{
    func displayWebtoonList(viewModels: [WebtoonHome.WebtoonList.ViewModel])
}

class WebtoonHomeViewController: UIViewController, WebtoonHomeDisplayLogic {
    var interactor: WebtoonHomeBusinessLogic?
    var router: (NSObjectProtocol & WebtoonHomeRoutingLogic & WebtoonHomeDataPassing)?
    
    private let mainScrollView: UIScrollView
    private let mainScrollStackView: UIStackView
    private let topEventScrollView: UIScrollView
    private let webtoonListScrollView: UIScrollView
    private let webtoonListStackView: UIStackView
    private let mondayWebtoonCollection: UICollectionView
    private let tuesdayWebtoonCollection: UICollectionView
    private let wednesdayWebtoonCollection: UICollectionView
    private let thursdayWebtoonCollection: UICollectionView
    private let fridayWebtoonCollection: UICollectionView
    private let saturdayWebtoonCollection: UICollectionView
    private let sundayWebtoonCollection: UICollectionView
    private let everyDayPlusCollection: UICollectionView
    
    private let webtoonListLayout: WebtoonListLayout
    private let mondayDataSource: WebtoonListDataSource
    private let tuesdayDataSource: WebtoonListDataSource
    private let wednesdayDataSource: WebtoonListDataSource
    private let thursdayDataSource: WebtoonListDataSource
    private let fridayDataSource: WebtoonListDataSource
    private let saturdayDataSource: WebtoonListDataSource
    private let sundayDataSource: WebtoonListDataSource
    private let everyDayPlusDataSource: WebtoonListDataSource
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        mainScrollView = {
            let scrollView = UIScrollView()
            scrollView.translatesAutoresizingMaskIntoConstraints = false
            return scrollView
        }()
        mainScrollStackView = {
            let stackView = UIStackView()
            stackView.translatesAutoresizingMaskIntoConstraints = false
            stackView.axis = .vertical
            return stackView
        }()
        topEventScrollView = {
            let scrollView = UIScrollView()
            scrollView.translatesAutoresizingMaskIntoConstraints = false
            return scrollView
        }()
        webtoonListScrollView = {
            let scrollView = UIScrollView()
            scrollView.translatesAutoresizingMaskIntoConstraints = false
            scrollView.isPagingEnabled = true
            return scrollView
        }()
        webtoonListStackView = {
            let stackView = UIStackView()
            stackView.translatesAutoresizingMaskIntoConstraints = false
            stackView.axis = .horizontal
            return stackView
        }()
        everyDayPlusCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        mondayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        tuesdayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        wednesdayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        thursdayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        fridayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        saturdayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        sundayWebtoonCollection = {
            let layout = UICollectionViewFlowLayout()
            layout.sectionInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
            let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
            collectionView.translatesAutoresizingMaskIntoConstraints = false
            return collectionView
        }()
        
        webtoonListLayout = WebtoonListLayout(inset: 20)
        everyDayPlusDataSource = WebtoonListDataSource()
        mondayDataSource = WebtoonListDataSource()
        tuesdayDataSource = WebtoonListDataSource()
        wednesdayDataSource = WebtoonListDataSource()
        thursdayDataSource = WebtoonListDataSource()
        fridayDataSource = WebtoonListDataSource()
        saturdayDataSource = WebtoonListDataSource()
        sundayDataSource = WebtoonListDataSource()
        
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
        setupViews()
        setupDataSource()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WebtoonHomeInteractor()
        let presenter = WebtoonHomePresenter()
        let router = WebtoonHomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchAllWebtoonCollection()
    }
    
    private func setupViews() {
        title = "웹툰"
        tabBarItem = UITabBarItem(title: "웹툰", image: UIImage(systemName: "house"), selectedImage: UIImage(systemName: "house.fill"))
        view.backgroundColor = .white
        
        view.addSubview(mainScrollView)
        mainScrollView.addSubview(mainScrollStackView)
        mainScrollStackView.addArrangedSubview(topEventScrollView)
        mainScrollStackView.addArrangedSubview(webtoonListScrollView)
        webtoonListScrollView.addSubview(webtoonListStackView)
        
        let everydayPlusStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let mondayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let tuesdayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let wednesdayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let thursdayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let fridayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let saturdayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        let sundayStackView: UIStackView = {
            let stackView = UIStackView()
            stackView.axis = .vertical
            return stackView
        }()
        
        webtoonListStackView.addArrangedSubview(mondayStackView)
        webtoonListStackView.addArrangedSubview(tuesdayStackView)
        webtoonListStackView.addArrangedSubview(wednesdayStackView)
        webtoonListStackView.addArrangedSubview(thursdayStackView)
        webtoonListStackView.addArrangedSubview(fridayStackView)
        webtoonListStackView.addArrangedSubview(saturdayStackView)
        webtoonListStackView.addArrangedSubview(sundayStackView)
        webtoonListStackView.addArrangedSubview(everydayPlusStackView)
        everydayPlusStackView.addArrangedSubview(everyDayPlusCollection)
        mondayStackView.addArrangedSubview(mondayWebtoonCollection)
        tuesdayStackView.addArrangedSubview(tuesdayWebtoonCollection)
        wednesdayStackView.addArrangedSubview(wednesdayWebtoonCollection)
        thursdayStackView.addArrangedSubview(thursdayWebtoonCollection)
        fridayStackView.addArrangedSubview(fridayWebtoonCollection)
        saturdayStackView.addArrangedSubview(saturdayWebtoonCollection)
        sundayStackView.addArrangedSubview(sundayWebtoonCollection)
        
        NSLayoutConstraint.activate([
            mainScrollView.topAnchor.constraint(equalTo: view.topAnchor),
            mainScrollView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            mainScrollView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            mainScrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            
            mainScrollStackView.topAnchor.constraint(equalTo: mainScrollView.contentLayoutGuide.topAnchor),
            mainScrollStackView.leadingAnchor.constraint(equalTo: mainScrollView.contentLayoutGuide.leadingAnchor),
            mainScrollStackView.trailingAnchor.constraint(equalTo: mainScrollView.contentLayoutGuide.trailingAnchor),
            mainScrollStackView.bottomAnchor.constraint(equalTo: mainScrollView.contentLayoutGuide.bottomAnchor),
            mainScrollStackView.widthAnchor.constraint(equalTo: mainScrollView.frameLayoutGuide.widthAnchor),
            
            topEventScrollView.widthAnchor.constraint(equalTo: view.safeAreaLayoutGuide.widthAnchor),
            topEventScrollView.heightAnchor.constraint(equalToConstant: 150),
            
            webtoonListScrollView.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            webtoonListScrollView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor),
            
            webtoonListStackView.topAnchor.constraint(equalTo: webtoonListScrollView.contentLayoutGuide.topAnchor),
            webtoonListStackView.leadingAnchor.constraint(equalTo: webtoonListScrollView.contentLayoutGuide.leadingAnchor),
            webtoonListStackView.trailingAnchor.constraint(equalTo: webtoonListScrollView.contentLayoutGuide.trailingAnchor),
            webtoonListStackView.bottomAnchor.constraint(equalTo: webtoonListScrollView.contentLayoutGuide.bottomAnchor),
            webtoonListStackView.heightAnchor.constraint(equalTo: webtoonListScrollView.frameLayoutGuide.heightAnchor),

            mondayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            tuesdayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            wednesdayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            thursdayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            fridayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            saturdayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            sundayWebtoonCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor),
            everyDayPlusCollection.widthAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.widthAnchor)
        ])
    }
    
    private func setupDataSource() {
        mondayWebtoonCollection.delegate = webtoonListLayout
        mondayWebtoonCollection.dataSource = mondayDataSource
        mondayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        tuesdayWebtoonCollection.delegate = webtoonListLayout
        tuesdayWebtoonCollection.dataSource = mondayDataSource
        tuesdayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        wednesdayWebtoonCollection.delegate = webtoonListLayout
        wednesdayWebtoonCollection.dataSource = mondayDataSource
        wednesdayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        thursdayWebtoonCollection.delegate = webtoonListLayout
        thursdayWebtoonCollection.dataSource = mondayDataSource
        thursdayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        fridayWebtoonCollection.delegate = webtoonListLayout
        fridayWebtoonCollection.dataSource = mondayDataSource
        fridayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        saturdayWebtoonCollection.delegate = webtoonListLayout
        saturdayWebtoonCollection.dataSource = mondayDataSource
        saturdayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        sundayWebtoonCollection.delegate = webtoonListLayout
        sundayWebtoonCollection.dataSource = mondayDataSource
        sundayWebtoonCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
        everyDayPlusCollection.delegate = webtoonListLayout
        everyDayPlusCollection.dataSource = mondayDataSource
        everyDayPlusCollection.register(WebtoonListCell.self, forCellWithReuseIdentifier: WebtoonListCell.identifier)
    }
    
    private func setupMainStackViewSpacing() {
        mainScrollStackView.setCustomSpacing(5, after: topEventScrollView)
    }
    
    func fetchAllWebtoonCollection() {
        interactor?.fetchWebtoons()
    }
    
    func displayWebtoonList(viewModels: [WebtoonHome.WebtoonList.ViewModel]) {
        DispatchQueue.main.async { [weak self] in
            self?.everyDayPlusDataSource.update(dataSource: viewModels)
            self?.everyDayPlusCollection.reloadData()
            self?.mondayDataSource.update(dataSource: viewModels)
            self?.mondayWebtoonCollection.reloadData()
            self?.tuesdayDataSource.update(dataSource: viewModels)
            self?.tuesdayWebtoonCollection.reloadData()
            self?.wednesdayDataSource.update(dataSource: viewModels)
            self?.wednesdayWebtoonCollection.reloadData()
            self?.thursdayDataSource.update(dataSource: viewModels)
            self?.thursdayWebtoonCollection.reloadData()
            self?.fridayDataSource.update(dataSource: viewModels)
            self?.fridayWebtoonCollection.reloadData()
            self?.saturdayDataSource.update(dataSource: viewModels)
            self?.saturdayWebtoonCollection.reloadData()
            self?.sundayDataSource.update(dataSource: viewModels)
            self?.sundayWebtoonCollection.reloadData()
        }
    }
}
