//
//  WebtoonHomeModels.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WebtoonHome
{
    struct LastUpdate: Decodable {
        var lastUpdate: String
    }
    struct Webtoon: Decodable {
        var title: String
        var author: String
        var url: String
        var img: String
        var service: String
        var updateDays: [String]
        var fanCount: Int?
        var searchKeyword: String
        var additional: AdditionalInformation
    }
    struct AdditionalInformation: Decodable {
        var new: Bool
        var rest: Bool
        var up: Bool
        var adult: Bool
        var singularityList: [String]
    }
    enum WebtoonList
    {
        struct Request
        {
            var page: Int
            var perPage: Int
            var service: WebtoonSupplier
            var updateDay: UpdateDay
            
            static var defaultRequest = Request(page: 1,
                                                perPage: Int(Int16.max),
                                                service: .naver,
                                                updateDay: Date.makeTodayWeekday())
        }
        struct Response: Decodable
        {
            var lastUpdate: String?
            var webtoons: [Webtoon]
        }
        struct ViewModel: Hashable {
            var title: String
            var author: String
            var img: String
            var isNew: Bool
            var isAdult: Bool
            var isRest: Bool
            var isUp: Bool
            var isOver15: Bool
            var isFree: Bool
            var isWaitFree: Bool
        }
    }
}

