//
//  WebtoonHomeInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeBusinessLogic {
    func fetchWebtoons()
}

protocol WebtoonHomeDataStore {
    //var name: String { get set }
}

class WebtoonHomeInteractor: WebtoonHomeBusinessLogic, WebtoonHomeDataStore
{
    var presenter: WebtoonHomePresentationLogic?
    private var worker: WebtoonHomeWorker = WebtoonHomeWorker(service: WebtoonsAPI())
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchWebtoons() {
        worker.fetchAllWebtoons { response in
            self.presenter?.presentSomething(response: response)
        }
    }
}
