//
//  WebtoonHomeInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol WebtoonHomeBusinessLogic {
    func fetchSpecificDayWebtoons(option: WebtoonHome.WebtoonList.Request, isButtonPress: Bool)
    func updateCurrent(updateDay: UpdateDay)
    func fetchRecommandWebtoons()
}

protocol WebtoonHomeDataStore {
    //var name: String { get set }
}

class WebtoonHomeInteractor: WebtoonHomeBusinessLogic, WebtoonHomeDataStore {
    
    var presenter: WebtoonHomePresentationLogic?
    private var worker: WebtoonHomeWorker
    private var lastUpdateDay: UpdateDay?
    
    private let coreDataManager: CoreDataManager
    
    init() {
        worker = WebtoonHomeWorker(service: WebtoonsAPI())
        lastUpdateDay = nil
        coreDataManager = CoreDataManager(persistentContainerName: "WebtoonCacheModel")
    }
    
    func fetchSpecificDayWebtoons(option: WebtoonHome.WebtoonList.Request,
                                  isButtonPress: Bool) {
        self.worker.isAlreadyFetch(targetDate: option.updateDay) { [weak self] in
            if $0 {
                let fetchedData = self?.coreDataManager.fetchData(type: WebtoonEntity.self,
                                                                  predicate: option.updateDay)
                guard let fetchedData = fetchedData else {
                    self?.fetchWebtoons(option: option, isButtonPress: isButtonPress)
                    return
                }
                self?.sendToPresenterFromCoreData(fetchedData: fetchedData, updateDay: option.updateDay)
                if isButtonPress {
                    self?.moveToSpecificdayWebtoonlist(updateday: option.updateDay)
                }
            } else {
                self?.fetchWebtoons(option: option, isButtonPress: isButtonPress)
            }
        }
    }
    
    func fetchWebtoons(option: WebtoonHome.WebtoonList.Request,
                       isButtonPress: Bool) {
        if lastUpdateDay == option.updateDay {
            return
        }
        lastUpdateDay = option.updateDay
        worker.fetchSpecificDayWebtoons(updateDay: option.updateDay) { [weak self] response in
            guard let self = self else {
                return
            }
            response.webtoons.forEach {
                let entity = self.coreDataManager.makeEntity(className: "WebtoonEntity") as? WebtoonEntity
                entity?.save(value: $0)
                if isButtonPress {
                    self.moveToSpecificdayWebtoonlist(updateday: option.updateDay)
                }
            }
            UserDefaults.standard.setValue(Date.makeTodayToString(), forKey: option.updateDay.rawValue)
            self.presenter?.presentWebtoonList(response: response, updateDay: option.updateDay)
        }
        if isButtonPress {
            moveToSpecificdayWebtoonlist(updateday: option.updateDay)
        }
    }
    
    func sendToPresenterFromCoreData(fetchedData: [WebtoonEntity], updateDay: UpdateDay) {
        presenter?.presentWebtoonList(entity: fetchedData, updateDay: updateDay)
    }
    
    func updateCurrent(updateDay: UpdateDay) {
        self.lastUpdateDay = updateDay
    }
    
    func fetchRecommandWebtoons() {
        worker.fetchRecommandWebtoons { [weak self] response in
            guard let self = self else {
                return
            }
            self.presenter?.presentRecommandWebtoons(response: response)
        }
    }
    
    private func moveToSpecificdayWebtoonlist(updateday: UpdateDay) {
        let updateDayToInt: CGFloat = UpdateDay.makeUpdatedayToInt(updateDay: updateday)
        presenter?.presentSpecificDayWebtoons(offset: updateDayToInt)
    }
}
