//
//  WebtoonHomeInteractor.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WebtoonHomeBusinessLogic {
    func fetchTodayWebtoons()
    func fetchRecommandWebtoons()
}

protocol WebtoonHomeDataStore {
    //var name: String { get set }
}

class WebtoonHomeInteractor: WebtoonHomeBusinessLogic, WebtoonHomeDataStore
{
    var presenter: WebtoonHomePresentationLogic?
    private var worker: WebtoonHomeWorker
    private var currentWeekday: UpdateDay
    
    init() {
        worker = WebtoonHomeWorker(service: WebtoonsAPI())
        currentWeekday = Date.makeTodayWeekday()
    }
    
    func fetchTodayWebtoons() {
        worker.fetchSpecificDayWebtoons(updateDay: currentWeekday) { [weak self] response in
            guard let self = self else { return }
            self.presenter?.presentWebtoonList(response: response, updateDay: self.currentWeekday)
        }
    }
    
    func fetchRecommandWebtoons() {
        worker.fetchRecommandWebtoons { [weak self] response in
            guard let self = self else { return }
            self.presenter?.presentRecommandWebtoons(response: response)
        }
    }
}
