//
//  WebtoonHomeModels.swift
//  CleanWebtoon
//
//  Created by temp_name on 2023/06/21.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WebtoonHome
{
    struct WetoonsFormField {
        var page: Int
        var perPage: Int
        var service: WebtoonSupplier
        var updateDay: UpdateDay
    }
    struct Webtoon: Decodable {
        var title: String
        var author: String
    }
    enum WebtoonList
    {
        struct Request
        {
            var webtoonList: WetoonsFormField?
            
            init(webtoonList: WetoonsFormField? = nil) {
                self.webtoonList = webtoonList
            }
        }
        struct Response: Decodable
        {
            var lastUpdate: String?
            var webtoons: [Webtoon]
        }
        struct ViewModel {
            var title: String
            var author: String
        }
    }
}

